Error in events.ts file when ng build --prod.
ERROR in node_modules/jsgantt-improved/src/events.ts(197,51): error TS2339: Property 'forEach' does not exist on type 'NodeListOf<Element>'.